-- Genres and platforms become lists.
--
-- Generated by `prisma migrate dev --create-only` and then rewritten: the
-- generated version dropped both columns in the same statement that added the
-- new ones, which reaches the right schema having thrown away every genre and
-- platform already recorded. The columns are added, backfilled, and only then
-- dropped.
--
-- The old values are comma-joined — the search bar built the platform one by
-- joining RAWG's whole array, which is the bug this fixes — so splitting on a
-- comma and trimming recovers the list that was flattened into them. Entries are
-- capped at five here as well as in the resolver, so a row that predates the cap
-- does not come back over it.

-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "genres" TEXT[],
ADD COLUMN     "platforms" TEXT[];

-- Backfill from the single-valued columns.
UPDATE "Game" SET
  "genres" = COALESCE(
    (
      SELECT array_agg(value ORDER BY ordinality)
      FROM (
        SELECT btrim(part) AS value, ordinality
        FROM unnest(string_to_array(COALESCE("genre", ''), ',')) WITH ORDINALITY AS t(part, ordinality)
        WHERE btrim(part) <> ''
        LIMIT 5
      ) AS kept
    ),
    ARRAY[]::TEXT[]
  ),
  "platforms" = COALESCE(
    (
      SELECT array_agg(value ORDER BY ordinality)
      FROM (
        SELECT btrim(part) AS value, ordinality
        FROM unnest(string_to_array(COALESCE("platform", ''), ',')) WITH ORDINALITY AS t(part, ordinality)
        WHERE btrim(part) <> ''
        LIMIT 5
      ) AS kept
    ),
    ARRAY[]::TEXT[]
  );

-- AlterTable
ALTER TABLE "Game" DROP COLUMN "genre",
DROP COLUMN "platform";
